import type { SkillCategory } from "../types";

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    id: "languages",
    name: "Lenguajes de Programación",
    icon: "📝",
    skills: [
      {
        id: "cpp",
        name: "C++",
        category: "Lenguajes de Programación",
        proficiency: 60,
        iconName: "C++",
        iconColor: "#00599C",
      },
      {
        id: "java",
        name: "Java",
        category: "Lenguajes de Programación",
        proficiency: 99,
        iconName: "Java",
        iconColor: "#007396",
      },
      {
        id: "html",
        name: "HTML",
        category: "Lenguajes de Programación",
        proficiency: 100,
        iconName: "HTML",
        iconColor: "#E34C26",
      },
      {
        id: "css",
        name: "CSS",
        category: "Lenguajes de Programación",
        proficiency: 100,
        iconName: "CSS",
        iconColor: "#1572B6",
      },
      {
        id: "javascript",
        name: "JavaScript",
        category: "Lenguajes de Programación",
        proficiency: 95,
        iconName: "JavaScript",
        iconColor: "#F7DF1E",
      },
      {
        id: "typescript",
        name: "TypeScript",
        category: "Lenguajes de Programación",
        proficiency: 95,
        iconName: "TypeScript",
        iconColor: "#3178C6",
      },
      {
        id: "python",
        name: "Python",
        category: "Lenguajes de Programación",
        proficiency: 70,
        iconName: "Python",
        iconColor: "#3776AB",
      },
      {
        id: "sql",
        name: "SQL",
        category: "Lenguajes de Programación",
        proficiency: 75,
        iconName: "SQL",
        iconColor: "#003B57",
      },
    ],
  },
  {
    id: "frameworks",
    name: "Frameworks & Librerías",
    icon: "🧩",
    skills: [
      {
        id: "react",
        name: "React",
        category: "Frameworks & Librerías",
        proficiency: 95,
        iconName: "React",
        iconColor: "#61DAFB",
      },
      {
        id: "nextjs",
        name: "Next.js",
        category: "Frameworks & Librerías",
        proficiency: 80,
        iconName: "Next.js",
        iconColor: "#000000",
      },
      {
        id: "tailwindcss",
        name: "TailwindCSS",
        category: "Frameworks & Librerías",
        proficiency: 95,
        iconName: "TailwindCSS",
        iconColor: "#06B6D4",
      },
      {
        id: "bootstrap",
        name: "Bootstrap",
        category: "Frameworks & Librerías",
        proficiency: 85,
        iconName: "Bootstrap",
        iconColor: "#7952B3",
      },
      {
        id: "nodejs",
        name: "Node.js",
        category: "Frameworks & Librerías",
        proficiency: 95,
        iconName: "Node.js",
        iconColor: "#68A063",
      },
      {
        id: "express",
        name: "Express",
        category: "Frameworks & Librerías",
        proficiency: 90,
        iconName: "Express",
        iconColor: "#000000",
      },
      {
        id: "nestjs",
        name: "NestJS",
        category: "Frameworks & Librerías",
        proficiency: 98,
        iconName: "NestJS",
        iconColor: "#EA2845",
      },
    ],
  },
  {
    id: "backend",
    name: "Backend & APIs",
    icon: "🔌",
    skills: [
      {
        id: "restapi",
        name: "REST API",
        category: "Backend & APIs",
        proficiency: 96,
        iconName: "REST API",
        iconColor: "#009688",
      },
      {
        id: "jwt",
        name: "JWT Authentication",
        category: "Backend & APIs",
        proficiency: 100,
        iconName: "JWT Authentication",
        iconColor: "#000000",
      },
      {
        id: "microservices",
        name: "Microservicios",
        category: "Backend & APIs",
        proficiency: 85,
        iconName: "Microservicios",
        iconColor: "#326CE5",
      },
      {
        id: "websockets",
        name: "WebSockets",
        category: "Backend & APIs",
        proficiency: 65,
        iconName: "WebSockets",
        iconColor: "#010101",
      },
    ],
  },
  {
    id: "databases",
    name: "Bases de Datos & ORMs",
    icon: "💾",
    skills: [
      {
        id: "postgresql",
        name: "PostgreSQL",
        category: "Bases de Datos & ORMs",
        proficiency: 97,
        iconName: "PostgreSQL",
        iconColor: "#336791",
      },
      {
        id: "mysql",
        name: "MySQL",
        category: "Bases de Datos & ORMs",
        proficiency: 60,
        iconName: "MySQL",
        iconColor: "#00758F",
      },
      {
        id: "mongodb",
        name: "MongoDB",
        category: "Bases de Datos & ORMs",
        proficiency: 65,
        iconName: "MongoDB",
        iconColor: "#13AA52",
      },
      {
        id: "prisma",
        name: "Prisma ORM",
        category: "Bases de Datos & ORMs",
        proficiency: 98,
        iconName: "Prisma ORM",
        iconColor: "#2D3748",
      },
      {
        id: "typeorm",
        name: "TypeORM",
        category: "Bases de Datos & ORMs",
        proficiency: 90,
        iconName: "TypeORM",
        iconColor: "#FEA625",
      },
    ],
  },
  {
    id: "devtools",
    name: "Herramientas & DevOps",
    icon: "🛠️",
    skills: [
      {
        id: "git",
        name: "Git",
        category: "Herramientas & DevOps",
        proficiency: 95,
        iconName: "Git",
        iconColor: "#F1502F",
      },
      {
        id: "github",
        name: "GitHub",
        category: "Herramientas & DevOps",
        proficiency: 95,
        iconName: "GitHub",
        iconColor: "#181717",
      },
      {
        id: "docker",
        name: "Docker",
        category: "Herramientas & DevOps",
        proficiency: 60,
        iconName: "Docker",
        iconColor: "#2496ED",
      },
      {
        id: "vite",
        name: "Vite",
        category: "Herramientas & DevOps",
        proficiency: 98,
        iconName: "Vite",
        iconColor: "#646CFF",
      },
      {
        id: "postman",
        name: "Postman",
        category: "Herramientas & DevOps",
        proficiency: 90,
        iconName: "Postman",
        iconColor: "#FF6C02",
      },
    ],
  },
  {
    id: "other",
    name: "Otras Tecnologías & Conocimientos",
    icon: "✨",
    skills: [
      {
        id: "seo",
        name: "SEO",
        category: "Otras Tecnologías & Conocimientos",
        proficiency: 85,
        iconName: "SEO",
        iconColor: "#E37400",
      },
      {
        id: "positioning",
        name: "Posicionamiento",
        category: "Otras Tecnologías & Conocimientos",
        proficiency: 90,
        iconName: "Posicionamiento",
        iconColor: "#00D084",
      },
      {
        id: "accessibility",
        name: "Accesibilidad",
        category: "Otras Tecnologías & Conocimientos",
        proficiency: 95,
        iconName: "Accesibilidad",
        iconColor: "#0078D4",
      },
      {
        id: "ux",
        name: "UX Design",
        category: "Otras Tecnologías & Conocimientos",
        proficiency: 95,
        iconName: "UX Design",
        iconColor: "#1ABCFE",
      },
      {
        id: "ui",
        name: "UI Design",
        category: "Otras Tecnologías & Conocimientos",
        proficiency: 98,
        iconName: "UI Design",
        iconColor: "#DA291C",
      },
      {
        id: "prompteng",
        name: "Prompt Engineering",
        category: "Otras Tecnologías & Conocimientos",
        proficiency: 90,
        iconName: "Prompt Engineering",
        iconColor: "#412991",
      },
    ],
  },
];
