import type { SkillCategory } from "../types";

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    id: "languages",
    name: "Lenguajes de Programación",

    skills: [
      {
        id: "cpp",
        name: "C++",
        category: "Lenguajes de Programación",
        proficiency: 60,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/cplusplus.svg",
        iconColor: "#00599C",
      },
      {
        id: "java",
        name: "Java",
        category: "Lenguajes de Programación",
        proficiency: 99,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/java.svg",
        iconColor: "#007396",
      },
      {
        id: "html",
        name: "HTML",
        category: "Lenguajes de Programación",
        proficiency: 100,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/html5.svg",
        iconColor: "#E34C26",
      },
      {
        id: "css",
        name: "CSS",
        category: "Lenguajes de Programación",
        proficiency: 100,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/css3.svg",
        iconColor: "#1572B6",
      },
      {
        id: "javascript",
        name: "JavaScript",
        category: "Lenguajes de Programación",
        proficiency: 95,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/javascript.svg",
        iconColor: "#F7DF1E",
      },
      {
        id: "typescript",
        name: "TypeScript",
        category: "Lenguajes de Programación",
        proficiency: 95,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/typescript.svg",
        iconColor: "#3178C6",
      },
      {
        id: "python",
        name: "Python",
        category: "Lenguajes de Programación",
        proficiency: 70,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/python.svg",
        iconColor: "#3776AB",
      },
      {
        id: "sql",
        name: "SQL",
        category: "Lenguajes de Programación",
        proficiency: 75,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/sqlite.svg",
        iconColor: "#003B57",
      },
    ],
  },
  {
    id: "frameworks",
    name: "Frameworks & Librerías",

    skills: [
      {
        id: "react",
        name: "React",
        category: "Frameworks & Librerías",
        proficiency: 95,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/react.svg",
        iconColor: "#61DAFB",
      },
      {
        id: "nextjs",
        name: "Next.js",
        category: "Frameworks & Librerías",
        proficiency: 80,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/nextdotjs.svg",
        iconColor: "#000000",
      },
      {
        id: "tailwindcss",
        name: "TailwindCSS",
        category: "Frameworks & Librerías",
        proficiency: 95,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/tailwindcss.svg",
        iconColor: "#06B6D4",
      },
      {
        id: "bootstrap",
        name: "Bootstrap",
        category: "Frameworks & Librerías",
        proficiency: 85,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/bootstrap.svg",
        iconColor: "#7952B3",
      },
      {
        id: "nodejs",
        name: "Node.js",
        category: "Frameworks & Librerías",
        proficiency: 95,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/nodedotjs.svg",
        iconColor: "#68A063",
      },
      {
        id: "express",
        name: "Express",
        category: "Frameworks & Librerías",
        proficiency: 90,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/express.svg",
        iconColor: "#000000",
      },
      {
        id: "nestjs",
        name: "NestJS",
        category: "Frameworks & Librerías",
        proficiency: 98,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/nestjs.svg",
        iconColor: "#EA2845",
      },
    ],
  },
  {
    id: "backend",
    name: "Backend & APIs",

    skills: [
      {
        id: "restapi",
        name: "REST API",
        category: "Backend & APIs",
        proficiency: 96,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/fastapi.svg",
        iconColor: "#009688",
      },
      {
        id: "jwt",
        name: "JWT Authentication",
        category: "Backend & APIs",
        proficiency: 100,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/jsonwebtokens.svg",
        iconColor: "#000000",
      },
      {
        id: "microservices",
        name: "Microservicios",
        category: "Backend & APIs",
        proficiency: 85,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/kubernetes.svg",
        iconColor: "#326CE5",
      },
      {
        id: "websockets",
        name: "WebSockets",
        category: "Backend & APIs",
        proficiency: 65,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/socketdotio.svg",
        iconColor: "#010101",
      },
    ],
  },
  {
    id: "databases",
    name: "Bases de Datos & ORMs",

    skills: [
      {
        id: "postgresql",
        name: "PostgreSQL",
        category: "Bases de Datos & ORMs",
        proficiency: 97,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/postgresql.svg",
        iconColor: "#336791",
      },
      {
        id: "mysql",
        name: "MySQL",
        category: "Bases de Datos & ORMs",
        proficiency: 60,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/mysql.svg",
        iconColor: "#00758F",
      },
      {
        id: "mongodb",
        name: "MongoDB",
        category: "Bases de Datos & ORMs",
        proficiency: 65,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/mongodb.svg",
        iconColor: "#13AA52",
      },
      {
        id: "prisma",
        name: "Prisma ORM",
        category: "Bases de Datos & ORMs",
        proficiency: 98,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/prisma.svg",
        iconColor: "#2D3748",
      },
      {
        id: "typeorm",
        name: "TypeORM",
        category: "Bases de Datos & ORMs",
        proficiency: 90,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/typescript.svg",
        iconColor: "#FEA625",
      },
    ],
  },
  {
    id: "devtools",
    name: "Herramientas & DevOps",

    skills: [
      {
        id: "git",
        name: "Git",
        category: "Herramientas & DevOps",
        proficiency: 95,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/git.svg",
        iconColor: "#F1502F",
      },
      {
        id: "github",
        name: "GitHub",
        category: "Herramientas & DevOps",
        proficiency: 95,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/github.svg",
        iconColor: "#181717",
      },
      {
        id: "docker",
        name: "Docker",
        category: "Herramientas & DevOps",
        proficiency: 60,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/docker.svg",
        iconColor: "#2496ED",
      },
      {
        id: "vite",
        name: "Vite",
        category: "Herramientas & DevOps",
        proficiency: 98,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/vite.svg",
        iconColor: "#646CFF",
      },
      {
        id: "postman",
        name: "Postman",
        category: "Herramientas & DevOps",
        proficiency: 90,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/postman.svg",
        iconColor: "#FF6C02",
      },
      {
        id: "vercel",
        name: "Vercel",
        category: "Herramientas & DevOps",
        proficiency: 85, // Asigna un porcentaje según tu nivel de experiencia
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/vercel.svg",
        iconColor: "#FFFFFF", // Color blanco para Vercel (o el que prefieras)
      },
      {
        id: "render",
        name: "Render",
        category: "Herramientas & DevOps",
        proficiency: 50, // Asigna un porcentaje según tu nivel de experiencia
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/render.svg",
        iconColor: "#46E3B7", // Color característico de Render
      },
    ],
  },
  {
    id: "other",
    name: "Otras Tecnologías & Conocimientos",

    skills: [
      {
        id: "seo",
        name: "SEO",
        category: "Otras Tecnologías & Conocimientos",
        proficiency: 85,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/googleanalytics.svg",
        iconColor: "#E37400",
      },
      {
        id: "positioning",
        name: "Posicionamiento",
        category: "Otras Tecnologías & Conocimientos",
        proficiency: 90,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/chartline.svg",
        iconColor: "#00D084",
      },
      {
        id: "accessibility",
        name: "Accesibilidad",
        category: "Otras Tecnologías & Conocimientos",
        proficiency: 95,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/accessibility.svg",
        iconColor: "#0078D4",
      },
      {
        id: "ux",
        name: "UX Design",
        category: "Otras Tecnologías & Conocimientos",
        proficiency: 95,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/figma.svg",
        iconColor: "#1ABCFE",
      },
      {
        id: "ui",
        name: "UI Design",
        category: "Otras Tecnologías & Conocimientos",
        proficiency: 98,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/adobe.svg",
        iconColor: "#DA291C",
      },
      {
        id: "prompteng",
        name: "Prompt Engineering",
        category: "Otras Tecnologías & Conocimientos",
        proficiency: 90,
        icon: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/openai.svg",
        iconColor: "#412991",
      },
    ],
  },
];
